== Initial Config

!R1
conf t
hostname R1
line con 0
  logging sync
ip multicast-routing
int g0/1
  ip addr 10.1.1.1 255.255.255.0
  ip pim dense-mode
  no shut
int g0/2
  ip addr 156.1.1.1 255.255.255.0
  ip pim dense-mode
  no shut
end


!R2
conf t
hostname R2
ip multicast-routing
line con 0
  logging sync
int g0/1
  ip addr 10.1.1.2 255.255.255.0
  ip pim dense-mode
  no shut
int g0/2
  ip addr 27.1.1.2 255.255.255.0
  ip pim dense-mode
  no shut
end

!R3
enable
conf t
ip multicast-routing
line con 0
  logging sync
hostname R3
int g0/1
  ip addr 10.1.1.3 255.255.255.0
  no shut
end

!R4
conf t
ip multicast-routing
hostname R4
line con 0
  logging sync
int g0/1
  ip addr 10.1.1.4 255.255.255.0
  no shut
end


!R5
en
conf t
hostname R5
ip multicast-routing
line con 0
  logging sync
int g0/1
  ip addr 156.1.1.5 255.255.255.0
  no shut
end

!R6
en
conf t
ip multicast-routing
hostname R6
line con 0
  logging sync
int g0/1
  ip addr 156.1.1.6 255.255.255.0
  no shut
end

!R7
en
ip multicast-routing
conf t
hostname R7
line con 0
  logging sync
int g0/1
  ip addr 27.1.1.7 255.255.255.0
  no shut
end

 
== Task: Enable PIM dense mode

Enable PIM dense mode on all interfaces of R1 and R2

== Task 2

Disable IP routing on R3 and R4 and configure their F0/0
interface to join 224.1.1.1 multicast group

!R3-4
conf t
no ip routing
int g0/1
  ip igmp join-group 224.1.1.1
end

