--- 
- name: Setup Base configs
  gather_facts: false
  hosts: localhost
  connection: local
  vars: 
    nodes: 
      - name: R1
        port: "5015"
      - name: R2
        port: "5010"
  tasks: 
    - name: no shutdown all management interfaces
      loop: {{ nodes }}
      telnet: 
        host: 127.0.0.1
        port: "{{ item.port }}"
        send_newline: yes
        timeout: 60 
        login_prompt: ''
        password_prompt: '' 
        prompts:
          - '[>|#]'
        commands:
          - configure terminal
          - interface GigabitEthernet 0/0
          - no shutdown
          - end
          - show ip int GigabitEthernet 0/0
        
