--- 
- name: Setup Base configs
  gather_facts: false
  hosts: localhost
  connection: local
  vars: 
    nodes: 
      - 5015
      - 5010
      - 5036
      - 5038
      - 5014
      - 5009
      - 5016
      - 5040
      - 5012
      - 5043
  tasks: 
    - name: load the baseline configuration
      with_items: "{{ nodes }}"
      telnet: 
        host: 127.0.0.1
        port: "{{ item }}"
        send_newline: yes
        timeout: 10 
        login_prompt: ''
        password_prompt: '' 
        prompts:
          - '[>|#]'
        commands:
          - configure replace flash:baseline.cfg
