= CDP

menu:Catalyst 3560-X Configuration Guides[ http://www.cisco.com/c/en/us/td/docs/switches/lan/catalyst3750x_3560x/software/release/15-0_2_se/configuration/guide/3750x_cg/swcdp.html[CDP] ]

== Overview 

- Layer 2 discovery protocol  running on Cisco devices
- Retrieves device type and SNMP agent address of neighboring devices

=== Packet format

- header followed by a set of TLV value

.CDP frame format
["packetdiag", target="cdp-frame-format"]
----
diagram {
  colwidth = 16
  node_height = 32
  default_node_color = lightyellow
  default_fontsize = 12

  * Version [len = 8, color = yellow]
  * TTL [len = 8, color = brown]
  * Type [len = 16, color = orange]
  * Length [len = 16, color = green ]
  * Value (variable) [len = 16, color = lime]
}
----

== CDP operations 

- Enable by default

.Task: Display global information about CDP characteristics
----
# show cdp

Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge
                 S - Switch, H - Host, I - IGMP, r - Repeater

Device ID        Local Intrfce     Holdtme    Capability  Platform  Port ID
Router3             Ser 1          120           R        2500      Ser 0
Router1             Eth 1          180           R        2500      Eth 0
Switch1             Eth 0          240           S        1900      2
----

----
show cdp entry <entry-name> [protocol | version]
----

.Task: Disable CDP 
----
(config)# no cdp run
----

.Task: Enable CDP on an interface
----
(config-if)# cdp enable
----

=== CDP updates

- default: 60 seconds range: 5-254 seconds

.Task: Set the transmission frequency of CDP updates in seconds
----
(config)# cdp timer <seconds>
----

.Task: Specify the amount of time a receiving device should hold the information sent by your device
----
(config)# cdp holdtime <seconds>
----

NOTE: default: 180 seconds, range: 10 to 255 seconds


=== Version

.Task: Send Version-2 advertisements
----
(config)# cdp advertise-v2
----



== Monitoring and maintenance

.Task: Reset the traffic counters to zero
----
clear cdp counters
----

=== Neighbors


.Task: Delete the CDP table of information about neighbors
----
clear cdp table
----


.Task: Display information about interfaces where CDP enabled
----
sh cdp interface [<interface-id>]
----

.Task: Display information about neighbors

----
sh cdp neighbors [<interface-id>] [detail]
----

.Task: Display CDP counters, including the number of packets sent and received and checksum errors

----
# show cdp traffic

Total packets output: 543, Input: 333
 Hdr syntax: 0, Chksum error: 0, Encaps failed: 0
 No memory: 0, Invalid: 0, Fragmented: 0
 CDP version 1 advertisements output: 191, Input: 187
 CDP version 2 advertisements output: 352, Input: 146
----
