= IDRP

menu:Configuration Guides[First Hop Redundancy Protocols > http://www.cisco.com/c/en/us/td/docs/ios-xml/ios/ipapp_fhrp/configuration/15-mt/fhp-15-mt-book/fhp-vrrp.html[IRDP] ]

== Overview

- ICMP Router Discovery Protocol allows hosts to locate routers
that can be used as gateway to reach IP-based devices on other networks.

- http://www.ietf.org/rfc/rfc1256.txt[RFC 1256]

=== Message format

.ICMP Router Advertisement Message
["packetdiag", target= 'icmp-router-advertisement']
------
{
  colwidth = 32
  node_height = 32
  default_node_color = lightyellow
  default_fontsize = 12

  * Type [len=8]
  * Code [len=8]
  * Checksum [len=16]
  * Num Addrs [len=8]
  * Addr Entry Size [len=8]
  * Lifetime [len=16]
  * Router Address  [len=32, stacked]
  * Preference Level [len=32, stacked] 
}
------

Type:: 9
Code:: 0
Checksum:: 
The 16-bit one's complement of the one's complement sum of the ICMP message, 
starting with the ICMP Type. 
For computing the checksum, the Checksum field is set to 0. 

Num Addrs:: Number of router addreses advertised in this message 
Addr Entry Size:: Number of 32-bit words of information per router address (=2 for IPv4)
Lifetime:: Maximum number of seconds that the router adresses may be considered valid.
Router Address[i]:: Sending router's addresses on the interface from which this message is sent.
Preference Level[i]:: Preferability of each Router Address[i] as a default router, 
relative to other router addresses on the same subnet. Higher values more preferable.



.ICMP Router Solicitation Message
["packetdiag", target= 'icmp-router-advertisement']
------
{
  colwidth = 32
  node_height = 32
  default_node_color = lightyellow
  default_fontsize = 12

  * Type [len=8]
  * Code [len=8]
  * Checksum [len=16]
  * Reserved [len=32]
}
------

Type:: 10
Code:: 0
Checksum:: 
The 16-bit one's complement of the one's complement sum of the ICMP message, 
starting with the ICMP Type. 
For computing the checksum, the Checksum field is set to 0. 
Reserved:: Sent as 0; ignored on reception.

== Configuration


Configure a gateway to discover routers 
that transmit IRDP router updates after disabling IP routing

----
no ip routing
ip gdp irdp [multicast]
----

Enable IRDP on an interface

----
(config-if)# ip irdp
----

Send IRDP Advertisement to the all-systems multicast addresses

----
(config-if)# ip irdp multicast
----

Set the IRDP period for which advertisements are valid.
----
(config-if)# ip irdp holdtime <seconds>
----

Sets the IRDP maximum interval between advertisements.

----
ip irdp maxadvertinterval <seconds>
----

Set the IRDP minimum interval between advertisements.

----
ip irdp minadvertinterval <seconds>
----

Set the IRDP preference level of the device

----
(config-if)# ip irdp preference <number>
----

Specify an IRDP address and preference to prozy-advertise

----
(config-if)# ip irdp address <a.b.c.d> <preference-level>
----




