= OSPF
:icons: font
:stem:
:experimental:

menu:Configuration Guides[IP Routing >  http://www.cisco.com/c/en/us/td/docs/ios-xml/ios/iproute_ospf/configuration/15-mt/iro-15-mt-book/configuring_ospf.html[OSPF] ]


== Overview

- Distance vector protocol

== Concepts 

=== introduction

- link-state interior gateway protocol  
- RFC 2328
- Dijkstra short path first algorithm
- classless protocol 
- Transport via IP protocol 89 
* multicasts to 224.0.0.5 for AllSPF routers and to 224.0.0.6 for Designated Routers
* unicasts 

- equal-cost multipath
- hierarchical design to reduce traffic
- authentication updates

=== Why use OSPF?

- Fast convergence

=== Neighbors

To form adjacency neighbors must agree on ...

- unique router ID
- unique interface IP address 
  * primary IP address for OSPFv2
  * link-local address for OSPFv3
- common attributes
  * interface area-id : 
  * authentication
  * hello and dead intervals
  * stub area flag
  * interface MTU ??
  * other optional capabilities


== Ospf cost 

latexmath:[cost = 10^8 / bandwidth(bps)]


.Task: Description
----
(config-router)# auto-cost reference-bandwitch <bps>
----


=== Common OSPF protocol header format

==== Packet types

.OSPF header format
["packetdiag", target="ospf-header-format",size=200]
----
diagram {
  colwidth = 32
  node_height = 32
  default_node_color = lightyellow
  default_fontsize = 12

  * Version [len=8]
  * Type [len=8]
  * Packet Length [len=16]
  * Router ID [len=32]
  * Area ID [len=32]
  * Checksum [len=16]
  * AuType [len=16]
  * Authentication [len=64]
}
----

Version::
    The OSPF version number (2). 
Type::
    Hello (1), database description (2), Link-State Request (3), Link-State Update (4), or Link-State Acknowledgment (5). 
Packet length::
    Length of the protocol packet in bytes including the OSPF header. 
Router ID::
    The ID of the router originating the packet. 
Area ID::
    The area that the packet is being sent into. 
Checksum::
    The standard IP checksum of the entire contents of the packet, excluding the 64-bit authentication field. 
AuType::
Identifies the authentication scheme to be used for the packet. 
- 0: no authentication
- 1: plain-text authentication
- 2: cryptographic authentication
Authentication::
    A 64-bit field for use by the authentication scheme. 


===== Hello Packet


.OSPF Hello Packet format
["packetdiag", target="ospf-hello-packet-format"]
----
diagram {
  colwidth = 32
  node_height = 32
  default_node_color = lightyellow
  default_fontsize = 12
  * OSPF packet header (24 bytes) [len=32, style=dotted, color=white]
  * Network mask [len=32]
  * Dead interval [len=16]
  * Hello interval [len=8]
  * Priority [len=8]
  * Designated Router [len=32]
  * Backup Designated Router [len=32]
  * Neighbor [len=32, stacked]
}
----

===== Database Description Packet

.OSPF Hello Packet format
["packetdiag", target="ospf-database-description-message-format"]
----
diagram {
  colwidth = 32
  node_height = 32
  default_node_color = lightyellow
  default_fontsize = 12
  * OSPF packet header (24 bytes) [len=32, style=dotted, color=white]
  * Interface MTU [len=16]
  * Options [len=8]
  * Reserved [len=5]
  * I [len=1]
  * M [len=1]
  * MS [len=1]
  * DD sequence number [len=32]
  * LSA header (20 bytes) [len=32, stacked]
}
----

Interface MTU:: 
Size of the largest IP message that can be sent on this router's interface
without fragmentation

Options::
For optional OSPF capabilities

I-bit::
Initial for the first in a sequence of DD messages

M-bit::
More DD follow this one

MS-bit::
if this message is sent by the master in the communication 

[format="csv", cols="10,30,60"]
|===
Type, Description, functionality
1, Hello, discover/maintain neighbors
2, Database description , summarize database contents
3, Link-state request, database download 
4, Link-state update, databases update
5, Link-state acknowledge, flooding acknowledgement
|===

===== Link State Request 

.OSPF Link State Request format
["packetdiag", target="ospf-link-state-request-message-format"]
----
diagram {
  colwidth = 32
  node_height = 32
  default_node_color = lightyellow
  default_fontsize = 12
  * LS type [len=32]
  * Link State ID [len=32]
  * Advertising router [len=32]
  * ... [len=32]
}
----

===== Link State Update 


.OSPF Link State Update format
["packetdiag", target="ospf-link-state-update-message-format"]
----
diagram {
  colwidth = 32
  node_height = 32
  default_node_color = lightyellow
  default_fontsize = 12
  * Number of LSAs [len=32]
  * LSAs [len=32, stacked]
}
----


===== Link State Acknowledgment 


.OSPF Link State Acknowledgment format
["packetdiag", target="ospf-link-state-ack-message-format"]
----
diagram {
  colwidth = 32
  node_height = 32
  default_node_color = lightyellow
  default_fontsize = 12
  * LSA headers [len=32, stacked]
}
----

LSA headers::
Contains LSA headers to identify the LSAs acknowledged.



=== Link-State Packets

Type 1::
  - Router LSA
  - generated by each router for each interface in the area
  - flooded only within the same area

Type 2::
  - Network LSA
  - generated by DR
  - describes the set of routers attached to a particular network
  - flooded only within the area that contains the network 

Type 3::
  - Summary inter-area LSA
  - Generated by ABR
  - describes inter-area routes to network

Type 4::
  - Summary inter-area LSA 
  - Generated by ABR
  - describes routes to ASBR
  - tells other other routers in the area how to get to the advertising router
    of an external route

Type 5::
  - AS external LSA
  - originated by ASBR
  - describes routes to destinations external to the AS
  - flooded all over except stub areas

NOTE:  OSPF's SPF algorithm links different pieces of information together. 
For a router in Area 1 to reach the external route in Area 3, 
it has to look at the Type-5 that represents the external route. 
Then it has to look at the Type-4 representing the ABR on the area that the ASBR lives in. 
Then we have to look at the Type-3 to get to that remote ABR. 
Finally we look at the Type-1 and Type-2 LSAs in our area to determine how to get to our closest ABR. 
Read more
https://supportforums.cisco.com/document/133976/reading-and-understanding-ospf-database#sthash.qdHPgN1P.dpuf[here].


== backbone and area 0

== Virtual links

- purposes:
  * Areas not physically connected to area 0 
  * partitioning the backbone

- transit area can not be stub

.Router A 
----
(config)# router ospf 10
(config-router)# area 2 virtual-link 2.2.2.2 
----

.Router B
----
(config)# router ospf 10
(config-router)# area 2 virtual-link 1.1.1.1
----



.Task: TODO
----
(config-router)# no capability transit
----



=== Adjacency

=== DR election

- There is no pre-emption in ospf
  * Router must wait for the failure of the current DR 
  * use the WAIT timer = DEAD timer

- on hub-and-spoke, best practice is to have hub as DR and spokes not eligible as DR with priority=0jgt


=== Router id

Determined by these rules in order of preference at boot or ospf process restart:

- manually configured router id
- highest IP address of an up/up loopback 
- highest IP address of an up/up non-loopack 


.Task: Set the router-id
----
(config-router)# router-id <a.b.c.d>
----

.Task: Priority
----
(config-if)# ip ospf priority <0-255>
----

.Task: Set the WAIT timer
----
(config-if)# ip ospf dead-timer <seconds>
----



=== network types

Point-to-point::
  - only 2 routers 
  - automatic neighbor relationships
  - no DR/BDR election
  - multicast hellos
  - default for HDLC and PPP

broadcast::
  - automatic neighbor discovery
  - DR/BDR election
  - default for ethernet, TR, FDDI
  - multicast hellos
  - DR doesn't change the next hop of advertised prefixes 

Non-broadcast::
  - unicast hellos
  - manual configuration of neighbor
  - DR/BDR election 
  - default on Frame Relay, X.25 and SMDS
  
Point-to-multipoint::
  - multi-access, broadcast
  - automatic discovery of neighbor (MA)
  - DR/BDR election
  - one IP subnet
  - maintain connectivity during a VC failure ???
  - generates host routes (with mask /32 ) for each neighbor
  - default for ???

Point-to-multipoint non-broadcast::
  - manual configuration of neighbor
  - no DR/BDR election
  - network proprietary to Cisco

Loopback::


[TIP]
if Multi-Access network type then no DR/BDR election
if non-broadcast, then manual configuration of neighbors

http://www.cisco.com/c/en/us/support/docs/ip/open-shortest-path-first-ospf/7039-1.html#t27[OSPF design guide: selecting interface network types]


.OSPF network type compatibilities
[IMPORTANT]
====
- iakfsadfj
- adsfkjasdf
- asdfjsadfj
====


=== Graceful restart

- enables a router to continue to forward packets during a restart of the routing process
- must be configured on all neighbor routers 
- can also work with EIGRP, BGP, IS-IS
- default since IOS 12.4(6)T
- 2 versions: RFC 3623 and Cisco NSF 

http://www.cisco.com/en/US/docs/ios-xml/ios/iproute_ospf/command/ospf-a1.html#wp258289[Cisco
NSF]


=== SPF throttling



=== capability vrf-lite

Read OSG, chapter 19, VRF lite, pp. 872-876

http://www.cisco.com/en/US/docs/ios-xml/ios/iproute_ospf/command/ospf-a1.html#wp2582896905


=== summarization

Why the null 0 interface is added ?

- do prevent routing loops
  * packets destined for the routes that have been summarized will a longer  match
  * packets destined to summary routes will be dropped


See good explanation


=== OSPF states


Down::
- No hellos have been received from neighbors

Attempt::
- Unicast hello packet has been sent to neighbor, but not yet received back
- only used for manually configured NBMA neighbors

Init::
- I have received a hello packet from a neighbor,
but they have not acknowledged a hello from me

2-way::
- I have received a hello packet from a neighbor 
and he acknowledged a hello from me
- I can see my Router Id in the neighbor's hello packet
- Stop here for DROthers


Exstart::
- Master & slave relationship is formed where master has higher router-id
- Master chooses the starting sequence number ofr the DBD packets that are
  used for actual LSA exchange.

Exchange::
- Local link state database is sent through DBD packets
- DBD sequence number is used for reliable acknowledgement/retransmission


Loading::
- LSR packets are sent to ask for more info about a particular LSA


Full::
- Neighbors are fully adjacent and databases are synchronized.


== OSPF process

.Task: Enable OSPF process (legacy command )
----
(config)# router ospf <process-id>
(config-router)# network <a.b.c.d> [w.i.l.d] area <id> 
----

[NOTE] 
====
- inject both the primary and secondary addresses
- If an interface is IP unnumbered, and there is a *network* statement
that matches the IP address of the primary interface,
inject both the primary interface and the unnumbered interface 
====


.Task: Enable OSPF Process (interface level)
----
(config-if)# ip ospf <process-id> area <id> secondaries none
----



.Task: Prevent OSPF to advertize secondary prefixes
----
(config-if)# ip ospf <process-id> area <id> secondaries none
----

=== OSPF authentication

- Null , default: type 0

- Plain-text, simple password authentication 

----
(config-router)# area <id> authentication  
(config-if)# ip ospf authentication-key <string> 
----

- Message digest authentication

----
(config-router)# area <id> authentication message-digest  
(config-if)# ip ospg message-digest-key key-id md5 <string> 
----

- Message digest 



== Configure OSPF interface parameters


=== configure spf timers

----
(config-router)# timers spf seconds <seconds>
----

- spf-delay: between topology change notifications and recalculation of the shortest path
- spf-holdtime : between spf calculations


=== configure spf throttling

----
spf ???
----

.Task: Ensure that one router performs LSA translation in a NSSA area
TODO



== readings

http://www.cisco.com/en/US/tech/tk365/technologies_tech_note09186a0080094aaa.shtml[What
are ospf areas and virtual links]

http://www.cisco.com/en/US/tech/tk365/technologies_white_paper09186a0080094e9e.shtml#appa1[ospf
design guide: link-state advertisements]


