= AAA

== Local AAA Server

The Local AAA Server feature allows you to configure your router so that user authentication
and authorization attributes currently available on AAA servers are available locally on the
router. The attributes can be added to existing framework, such as the local user database or
subscriber profile. The local AAA server provides access to the complete dictionary of Cisco
IOS supported attributes.

You can configure your router so that AAA authentication and authorization attributes currently
available on AAA servers are made available on existing Cisco IOS devices. The attributes can
be added to existing framework, such as the local user database or subscriber profile. For
example, an attribute list can now be added to an existing username, providing the ability for the
local user database to act as a local AAA server. For situations in which the local username list
is relatively small, this flexibility allows you to provide complete user authentication or
authorization locally within the Cisco IOS software without having a AAA server. This ability can
allow you to maintain your user database locally or provide a failover local mechanism without
having to sacrifice policy options when defining local users.
A subscriber profile allows domain-based clients to have policy applied at the end-user service
level. This flexibility allows common policy to be set for all users under a domain in one place
and applied there whether or not user authorization is done locally.


Further Reading
http://goo.gl/aaTqf5


== PPP Security

TODO



