= BFD

menu:Configuration Guides[IP Routing > http://www.cisco.com/c/en/us/td/docs/ios-xml/ios/iproute_bfd/configuration/15-mt/irb-15-mt-book/irb-bi-fwd-det.html[Bidirectional Forwarding Detection] ]


- http://tools.ietf.org/html/rfc5880[RFC 5880]

   independently of media, data protocols, and routing protocols.

- provides a low-overhead, sub-second method of detecting failures in the
forwarding path between two adjacent routers, including the interfaces, data
links, and forwarding engines.

- detection protocol enabled at the interface and protocol levels.
* supports BFD asynchronous mode, which depends on the sending of
BFD control packets between two systems to activate and maintain BFD neighbor
sessions between routers.
* must be configured on both systems (or BFD peers)

- benefits of implementing BFD over reduced timer mechanisms for EIGRP, IS-IS, and OSPF:
* sub-second failure detection ( vs 1 or 2 seconds )
* not tied to any any particular routing protocol or media
* less CPU-intensive because some parts of BFD can be distributed to the data plane (vs control plane )

- always run in a unicast, point-to-point mode.
- UDP
* BFD control packets sourced from 49152 and sent to 3784.
* BFD echo packets sourced from 3785 and sent to 3785


== BFD Control Packet Format

- Mandatory  Control section + Optional Authentication section

.BFD Control Packet Format
[packetdiag, target="bfd-header-format",size=200]
----
diagram {
  colwidth = 32
  node_height = 32
  default_node_color = lightyellow
  default_fontsize = 12
  * Version [len=3]
  * Diag [len=5]
  * Sta [len=3]
  * P [len=1]
  * C [len=1]
  * A [len=1]
  * D [len=1]
  * M [len=1]
  * Detect Mult [len=8]
  * Length [len=8]
  * My Discriminator [len=32]
  * Your Discriminator [len=32]
  * Desired Min TX Interval [len=32]
  * Required Min RX Interval [len=32]
  * Required Min Echo RX Interval [len=32]
}
----


Diagnostic Code(Diag):: local system's reason for the last change in session state.
- 0 No Diagnostic
- 1 Control Detection Time Expired
- 2 Echo Function Failed
- 3 Neighbor Signaled Session Down
- 4 Forwarding Plane Reset
- 5 Path Down
- 6 Concatenated Path Down
- 7 Administratively Down
- 8 Reverse Concatenated Path Down
- 9-31 Reserved for future use

State (Sta):: Current BFD session state as seen by the transmitting system.
- 0  AdminDown
- 1  Down
- 2  Init
- 3  Up


 Poll (P)::
- If set, the transmitting system is requesting verification of
  connectivity, or of a parameter change, and is expecting a packet
  with the Final (F) bit in reply.

Fnal (F)::
- If set,  If set, the transmitting system is responding to a received BFD
  Control packet that had the Poll (P) bit set.

Control Plane Independent (C)::
- If set, the transmitting system's BFD implementation does not
share fate with its control plane (in other words, BFD is
implemented in the forwarding plane and can continue to function
through disruptions in the control plane).

Authentication Present (A)::
- If set, the Authentication Section is present and the session is
to be authenticated

Demand (D)::
- If set, Demand mode is active in the transmitting system (the
system wishes to operate in Demand mode, knows that the session is
Up in both directions, and is directing the remote system to cease
the periodic transmission of BFD Control packets).

Multipoint (M)::
- Reserved for future point-to-multipoint extensions to
- Must be zero on both transmit and receipt.

Detection Time Multiplier (Detect Mult)::
-  The negotiated transmit interval, multiplied by this value, provides the Detection Time for the
receiving system in Asynchronous mode.

Length::
- Length of the BFD Control packet, in bytes.

My Discriminator:: Unique, nonzero discriminator value generated by the transmitting system
- Used to demultiplex multiple BFD sessions
between the same pair of systems.

Your Discriminator::
- The discriminator received from the corresponding remote system.
  This field reflects back the received value of My Discriminator,
  or is zero if that value is unknown.

Desired Min TX Interval::  minimum interval in microseconds, that the local
system would like to use when transmitting BFD Control packets, less any jitter applied
- The value zero is reserved.

Required Min RX Interval:: minimum interval, in microseconds, between received
  BFD Control packets that this system is capable of supporting,
  less any jitter applied by the sender.
- If this value is zero, the transmitting system does not want the
  remote system to send any periodic BFD Control packets.

- Required Min Echo RX Interval: minimum interval, in microseconds, between received
  BFD Echo packets that this system is capable of supporting, less
  any jitter applied by the sender .
  - If this value is zero, the transmitting system does not support the
  receipt of BFD Echo packets.

.Optional Authentication Section
[packetdiag, target="bfd-authentication-format",size=200]
----
diagram {
  colwidth = 32
  node_height = 32
  default_node_color = lightyellow
  default_fontsize = 12
  * Auth Type [len=8]
  * Auth Len [len=8]
  * Auth Data ... [len=16]
}
----

Auth Type::
- 0  Reserved
- 1  Simple Password
- 2  Keyed MD5
- 3  Meticulous Keyed MD5
- 4  Keyed SHA1
- 5  Meticulous Keyed SHA1
- 6-255  Reserved for future use

Auth Len:: length, in bytes, of the authentication section, including the
  Auth Type and Auth Len fields.


== BFD operating modes

Asynchronous mode:: The systems periodically send BFD Control packets to one
another, and if a number of those packets in a row are not received by the
other system, the session is declared to be down.
- requires half as many packets to achieve a particular Detection Time as does the Echo function.
- used when the Echo function cannot be supported for some reason.

Demand mode:: It is assumed that a system has an independent way of verifying
that it has connectivity to the other system.  Once a BFD session is
established, such a system may ask the other system to stop sending BFD Control
packets, except when the system feels the need to verify connectivity
explicitly, in which case a short sequence of BFD Control packets is exchanged,
and then the far system quiesces.  Demand mode may operate independently in
each direction, or simultaneously.
- useful in situations where the overhead of a periodic
   protocol might prove onerous, such as a system with a very large
   number of BFD sessions.
- useful when the Echo function is
   being used symmetrically.
- may not be used when the path round-trip time is greater than
   the desired Detection Time, or the protocol will fail to work
   properly

Echo mode::
- Enabled by default,
* can be used with both Asynchronous and Demand mode
* can be disabled to run independently in each direction.
* Described as _without asymmetry_ when it is running on both sides (both BFD neighbors are running echo mode).

- works asynchronously between 2 BFD neighbors R1 and R2
* R1 sends an echo packet (instead of a control packet) to R2, formatted as:

  L3 Source: R1 (192.168.12.1)
  L3 Destination: R1 (192.168.12.1)
  MAC Source: Itself (000c.298f.aca3)
  MAC Destination: (000c.29cf.21ff)

* R2's receives this packet, sees this packet, and CEF-switches it straight back to R1!
* In this fashion, R1 knows that R2 is reachable.
* R2 would perform similar behavior towards R1, for it's own echo process.

- Control-plane CPU-intensive packets are still sent, but they are sent at the "slow timers" speed.

[CAUTION]
====
- Before using BFD echo mode, disable ICMP redirect messages ( *no ip redirects* command ) to avoid high CPU utilization.
- Don't enable bothBFD echo mode and uRPF. The session will flap
====

.Task: Disable BFD Echo Mode Without Asymmetry
----
(config)# no bfd echo
----
NOTE: No echo packets will be sent by the router, and the router will not forward BFD echo packets that are received from any neighbor routers.

.Task: Configure the BFD slow timer.
----
(config-if)# bfd slow-timer <milliseconds>
----





== BFD Session Parameters on the Interface


[horizontal]
interval:: Rate in milliseconds (50..999) at which BFD control packets will be sent to BFD peers.
min_rx:: Rate in milliseconds (50..999) at which BFD control packets will be expected to be received from BFD peers.
multiplier:: Number (3..50) of consecutive BFD control packets that must be missed from a BFD peer before BFD declares that the peer is unavailable and the Layer 3 BFD peer is informed of the failure.


.Task: Enables BFD on the interface.
----
(config-if)# bfd interval <milliseconds> min_rx <milliseconds> multiplier <interval-multiplier>
----
[NOTE]
====
- The bfd interval configuration is removed when the subinterface on which it is configured is removed.
- The bfd interval configuration is not removed when:
  ** an IPv4 address is removed from an interface
  ** an IPv6 address is removed from an interface
  ** IPv6 is disabled from an interface
  ** an interface is shutdown
  ** IPv4 CEF is disabled globally or locally on an interface
  ** IPv6 CEF is disabled globally or locally on an interface
====


== BFD Support for Dynamic Routing

- BFD has no neighbor detection.
* When the routing protocol needs to monitor a neighbor, it informs BFD, and BFD establishes the neighbor relationship at that point.

- Various routing protocols can piggyback a single BFD session.
* If you have BGP and EIGRP running between the same two subnets on the same two routers, there's no need to have two BFD sessions for checking the same exact topology.

- enabled globally at the router level or a per interface basis

.Task: Enable BFD for all interfaces participating in the routing process
----
(config-router)#  bfd all-interfaces
----

.Task: Enable BFD for all interfaces participating in the routing process. Use address-family interface configuration mode
----
(config-router-af-interface)# bfd
----

.Task: Configure BFD for BGP
----
(config-router)# neighbor <ip-address> fall-over bfd
----

.Task: Enable HSRP support for BFD on the interface.
----
(config-if)# standby bfd
----
NOTE: CEF must be enabled



.Task: Display a line-by-line listing of existing BFD adjacencies
----
# sh bfd neighbors
----

[NOTE]
.Sample Output
====
[listing]
OurAddr       NeighAddr      LD/RD RH  Holdown(mult) State     Int
 172.16.10.1   172.16.10.2    1/6  1   260  (3 )      Up        Fa0/1
====

.Task: Display a line-by-line listing of existing BFD adjacencies with details
----
# sh bfd neighbors details
----

[NOTE]
.Sample Output
====
[listing]
NeighAddr                         LD/RD    RH/RS     State     Int
 10.1.1.2                           1/1         1(RH) Up        Et0/0
 Session state is UP and not using echo function.
 OurAddr: 10.1.1.1
 Local Diag: 0, Demand mode: 0, Poll bit: 0
 MinTxInt: 50000, MinRxInt: 50000, Multiplier: 3 Received MinRxInt: 50000, Received
Multiplier: 3 Holddown (hits): 150(0), Hello (hits): 50(2223) Rx Count: 2212, Rx Interval
(ms) min/max/avg: 8/68/49 last: 0 ms ago Tx Count: 2222, Tx Interval (ms) min/max/avg:
40/60/49 last: 20 ms ago Elapsed time watermarks: 0 0 (last: 0) Registered protocols: CEF Stub
 Uptime: 00:01:49
 Last packet: Version: 0                  - Diagnostic: 0
              I Hear You bit: 1           - Demand bit: 0
              Poll bit: 0                 - Final bit: 0
              Multiplier: 3               - Length: 24
              My Discr.: 1                - Your Discr.: 1
              Min tx interval: 50000      - Min rx interval: 50000
              Min Echo interval: 50000
====


TIP: Read  https://brbccie.blogspot.co.za/2014/06/everything-bfd.html[Jeff Kronlage's blog on BFD]


== BFD Support for Static Routing

- Supports RIPv2, EIGRP, OSPF, IS-IS, BGP, HSRP

.Task: Specifies a static route BFD neighbor.
----
(config)# ip route static bfd <interface-type number> <ip-address> [group <group-name> [passive]]
----
[NOTE]
====
The *interface-type*, *interface-number*, and *ip-address* arguments are required because BFD support exists only for directly connected neighbors.
====

.Task: Displays information about the static BFD configuration from the configured BFD groups and nongroup entries
----
# sh ip static route bfd
----

== BFD Templates for Multi-Hop

- Template can be used to define timers and authentication independently from the interface
- use *bfd map* to associate the template with unique source-destination address pairs for multihop BFD sessions.

.Task: Configure a BFD template
----
configure terminal
  bfd-template multi-hop <template-name>
  interval min-tx <milliseconds> min-rx <milliseconds> multiplier <multiplier-value>
  authentication <authentication-type> keychain <keychain-name>
----

.Task: Configure a BFD Map
----
(config)# bfd mapipv4 vrf <name> <destination> <length> <source-address> <length> <template-name>
----

== BFD Multihop Support for IPv4 Static Routes

NOTE: The following section can be skipped

- Enables detection of IPv4 network failure between paths that are not directly connected.
* If a BFD session is up , IPv4 static routes that are associated with IPv4 static BFD configuration are added to a routing table.
If the BFD session is down, the routing table removes all associated static routes from the routing table.

- Applicable on different kinds of interfaces such as physical, subinterface, and virtual tunnels and across intra-area and interarea topologies.

=== BFDv4 Associated Mode

In BFDv4 associated mode, an IPv4
static route is automatically associated with an IPv4 static BFDv4 multihop
destination address if the static route next hop exactly matches the static
BFDv4 multihop destination address.

The state of the BFDv4 session is used to determine whether the associated IPv4
static routes are added in the IPv4 RIB. For
example, static routes are added in the IPv4 RIB only if the BFDv4 multihop
destination is reachable, and the static routes are removed from the IPv4 RIB
if the BFDv4 multihop destination subsequently becomes unreachable.

=== BFDv4 Unassociated Mode

In unassociate mode, a BFD neighbor is not associated with a static route, and the BFD
sessions are requested if the IPv4 static BFD is configured.

Unassociated mode is useful in the following scenario:

- Absence of an IPv4 static route—This scenario occurs when a static route is on
device A, and device B is the next hop. In associated mode, you must create
both a static BFD multihop destination address and a static route on both
devices to bring up the BFDv4 session from device B to device A. Specifying the
static BFD multihop destination in unassociated mode on device B avoids the
need to configure an unwanted static route.


.Task: Configuring BFD Multihop IPv4 Static Routes
----
# ip route static bfd <multihop-destination-address> <multihop-source-address> unassociate
----
[NOTE]
.Before you begin the configuration
====
- Specify a BFD destination address which is same as the IPv4 static route next hop or gateway address.
- Configure a BFD map and a BFD multihop template for an interface on the device. The destination address and source address configured for a BFD map must match the BFD static multihop configuration and the source address must be a valid IP address configured for an interface in the routing table.
====


== BFD on Multiple Hops

- for a destination more than one hop, and up to 255 hops, away
- Cisco IOS Release 15.1(3)S and later

- set up between a unique source-destination address pair provided by the client.
- need to  configure the *bfd-template* and *bfd map* commands to create a multihop template and associate it with one or more maps of destinations and associated BFD timers. You can enable authentication and configure a key chain for BFD multihop sessions.


== BFD dampening

- configures exponential delay mechanism to suppress the excessive effect of remote node reachability events flapping with BFD.
- improves the convergence time and stability throughout the network
- can be applied to all types of BFD sessions, including IPv4/single-hop/multihop, MPLS-TP, and Pseudo Wire (PW) Virtual Circuit Connection Verification (VCCV).
- can be configured at the BFD template level (both single-hop and multihop templates).
* Dampening is applied to all the sessions that use the BFD template.
* If you do not want a session to be dampened, you should use a new BFD template without dampening for the new session.
* not enabled by default




.Task: Configure a device to dampen a flapping BFD session.
----
(config-bfd)# dampening [ <half-life-period> <reuse-threshold> <suppress-threshold> <max-suppress-time>]
----
