= DTP


== Dynamic Trunk Protocol

- negotiate trunk status
- default to *dynamic auto*
- both sides must be on the same VTP domain or one must be in the NULL domain

.Trunking Configuration Options That Lead to a Working Trunk
[cols="20,10,40,20", format="dsv", options="header", grid="rows"]
|===
Configuration Command : Short name : Meaning : To trunk other side must be
switchport mode trunk : Trunk:  Always trunks on this end; sends DTP to help other side choose to trunk: On, desirable, auto
switchport mode trunk ; switchport nonegotiate: Nonegotiate: Always trunks on this end; does not send DTP messages (good when other switch is a non-Cisco switch): On
switchport mode dynamic desirable:  Desirable: Sends DTP messages, and trunks if negotiation succeeds: On, desirable, auto
switchport mode dynamic auto: Auto: Replies to DTP messages, and trunks if negotiation succeeds: On, desirable
switchport mode access: Access: Never trunks; sends DTP to help other side reach same conclusion : Never trunks
switchport mode access; switchport nonegotiate : Access (with nonegotiate): Never trunks; does not send DTP messages: (Never trunks)
|===

.Task: Configure an Inter-Switch Link to Be In Dynamic Desirable State
----
(config-if)# switchport mode dynamic desirable
----

.Task: Disable DTP for a Port Administratively Configured As a Trunk
----
(config-if)# switchport mode trunk
(config-if)# switchport nonegotiate
----

.Task: Put the Interface Into Permanent Nontrunking Mode
----
(config-if)# switchport mode access
----

.Task: Display a Summary Of Trunk-Related Information
----
show interface trunk: Summary of trunk-related information
----

.Task: List Trunking Details for a Specified Interface
----
show interface <type number> trunk
----

.Task: List Nontrunking Details for a Particular Interface
----
show interface <type number> switchport
----

.Task: Display DTP Information for the Switch
----
# show dtp
----

.Task: Display DTP Information for a Specific Interface

----
# show dtp interface <type slot/number>
----

== Trunking Between a Switch and a Router

Because  DTP is not supported on Router

- on the router, create a sub-interface for each desired vlan
- on the switch, disable DTP and manually configure the trunk


.Task: Enable Trunking but Disable DTP for Routers
----
! SW1
conf t
int e0/0
  switchport trunk enc dot1q
  switchport mode trunk
  switchport nonegotiate

! R1
conf t
int e0/0.1
  enc dot1q <vlan-id> [native]
----

== Verify

What is TOS/TAT in

----
sh dtp interface fa 0/19
----

