= Embedded Event Manager

menu:Configuration Guides[Embedded Management > http://www.cisco.com/c/en/us/td/docs/ios-xml/ios/eem/configuration/15-mt/eem-15-mt-book/eem-overview.html[Embedded Event Manager Overview] ]

- in-box, event tracking management
- EEM Components:


* EEM server – an internal process that handles the interaction between the
publishers and subscribers.

* EEM publisher (detector) – software that screens events, publishes if there is
a policy match. Some of the different detectors are CLI, NetFlow, SNMP, syslog,
timers and counters.

* EEM subscriber (policy) – defines an event and actions to be taken. There are
two policy types, applets with IOS CLI and scripts written using TCL.



The creation of an EEM policy involves:

- Selecting the event for which the policy is run.
- Defining the event detector options associated with logging and responding to the event.
- Defining the environment variables, if required.
- Choosing the actions to be performed when the event occurs.








