= EIGRP

- classless protocol (VLSM, summarization)
- multiple routed protocol support (ipv4, ipx, appletalk, )
- uses its own transport protocol
  ** IP protocol 88: RTP
  ** uses multicast to 224.0.0.10 and unicast
- Administrative distance : 90 internal routes, 5 summary routes , 170 external routes
- Forms active neighbor adjacencies
- DUAL for loop-free topology and fast convergence
- granular metric
- unequal cost load balancing
- summarization
- Supports MD5 based authentication


== EIGRP messages

[horizontal]
Hello::
- multicast to 224.0.0.10
- do not require acknowlegment
- can be used as Ack if sent without data

Ack::
- unicast
- contains a nonzero acknowledgement number

Update::
- multicast or unicast

Query::
- multicast unless in response to a received query

Reply::
- unicast
- indicates that it does not need to go into Active state
because it has a FS

Request::
- unicast or multicast
- get specific info from neighbors
- used in route server applications


.Task: Exchange EIGRP packets only as unicast
----
(config-router)# neighbor <a.b.c.d> <interface-id>
----

.Task: Exchange EIGRP packets only as unicast
----
(config-router-af-interface)# neighbor <a.b.c.d> <interface-id>
----


.Task: debug EIGRP
----
debug ip eigrp packet [hello | ack | update } quey | reply]
----

== Neighbors

- discovered with Hello packets
- must agree on
** primary IPv4 subnet
** Autonomous System Number
** authentication
** K values

- do not need to agree on timers

.Task: Verify neighbor adjacencies
----
# sh ip eigrp neighbors [detail]
----

TIP: Check that the queue count is zero


== EIGRP Loop prevention techniques

== Split horizon

- Enable by default on all interfaces

.Task: Disable split horizon for EIGRP
----
(config-if)# no ip split-horizon eigrp <asn> 
----

.Task: Disable split horizon in named configuration
----
(config-router-af-interface)# no split-horizon 
----

== DUAL feasibility condition


== EIGRP reconvergence

- if the successor becomes unreachable,
  * if there is a feasible successor
    ** use the FS without local computation
  * else
    ** query the neighbors and put the route in active

- Transport: IP protocol 88
- Hello interval

== Metric

metric = 256 * [K1 x bandwidth + (k2 x bandwidth)/ (256 -load) + k3 x delay] x [k5 /( reliability + k4)]

- bandwith: 10^7^ / minimum bandwidth in Kbps
- delay: in tens-of-microseconds
- reliability: likelihood of successful packet transmission with 0 means 0% and 255 means 100%
- load : effective load of the route with 255 means 100% loading
- mtu : minimum Maximum transmission unit

- default values: k1,k2,k3,k4,k5 = 1,0,1,0,0
- the values of K must match for the neighbors to become adjacents

.Task: Description
----
(config-router)# metric weights
----


== Wide Metric

Metric = [(K1*Minimum Throughput + (K2*Minimum Throughput/(256-Load) + (K3*Total Latency) + (K6*Extended Attributes)]* [K5/(K4 + Reliability)] 

== EIGRP Autonomous System Configuration

- created with the command  *router eigrp* <autonomous-system-number>
- EIGRP VPNs can be configured only under IPv4 address family. A VRF instance and route distinguisher must be defined before the address family session can be created.
- recommendation: configure the asn when the address family is configured by *router eigrp* <asn> *address-family* or seperately using the *autonomous-system* command.

== EIGRP Named Configuration

- Global params under SAFI or in *config-router-topology base* mode
- interface params in *config-router-af-interface* mode 
- wide-meric scaling automatic enabled

- can be configured in IPv4 and IPv6 named configuration
- VRF instance and a RD are optional
- EIGRP IPv6 VRF-lite feature is available only in EIGRP named configuration
- EIGRP VPNs can be configured. A VRF and RD must be defind before the address-family session can be created.
- a single EIGRP routing process can support multiple VRFs.  However, a single VRF can be supported by each VPN . Redistribution between VRFs is not supported.

.Task: Configure a basic EIGRP named configuration
----
(config)# router eigrp <virtual-instance-name>
(config-router)# address-family ipv4 [multicast] [umicast] [vrf <vrf-name>] autonomous-system <asn>
(config-router-af)# network <a.b.c.d>
----

== EIGRPv3

----
(config-router)# address-family ipv6 [unicast] [vrf vrf-name] autonomous-system asn
----

== EIGRP Neighbor Relationship Maintenance

- Hellos
- adjancency


== DUAL Finite State Machine

- A successor is a neighboring router that has a least-cost path to a
  destination that is guarentedd not to be part of a routinf

- Feasibility condition: RD < FD

== Protocol-Dependent Modules



== Goodbye Message

- broadcast when an EIGRP routing process is shut down
- Speeds convergence as peers don't have to wait the hold timer expiration

- Normal message displayed by routers that support Good Bye message
----
*Apr 26 13:48:42.523: %DUAL-5-NBRCHANGE: IP-EIGRP(0) 1: Neighbor 10.1.1.1
(Ethernet0/0) is down: Interface Goodbye received
----

- Misleading message displayed by router which doesn't support the Goodbye message
----
*Apr 26 13:48:41.811: %DUAL-5-NBRCHANGE: IP-EIGRP(0) 1: Neighbor
(Ethernet0/0) is down: K-value mismatch
----

** The receipt of a goodbye message by a non supporting peer does not disrupt normal network operations.
** The nonsupporting peer will terminate the session when the hold timer expires
** The sending and receiving routers will converge normally after the sender reloads


== Routing Metric Offset Lists

== EIGRP Cost Metrics


== Summarization

- All subnets are suppressed

.Task: Enable auto-summarization
----
(config-router)# auto-summarization
----
[NOTE]
====
- Cannot be used in divergent networks
- create null0 summary
====

.Task: Advertise a single summary in EIGRP classic mode
----
(config-if)# ip summary-address eigrp <asn> <prefix> <mask>
----

.Task: Advertise a single summary in EIGRP named mode
----
(config-router-af-interface)# summary-address <prefix> <mask>
----

.Task: Configure summarization to advertise a default route into EIGRP
----
(config-if)# ip summary-address eigrp <asn> 0.0.0.0 0.0.0.0
----
[NOTE]
====
- All subnets will be suppressed because all IPv4 networks are subnet of 0/0
====

=== Leak map

.Task: Advertise specific subnets of a EIGRP summary
----
(config-if)# ip summary-address eigrp <asn> <prefix> <mask> leak-map <route-maps>
----

=== Floating Summary Routes

TODO
- By default, summarization install a route to Null0 to match the summary 
  to prevent forwarding traffic for unreachable destinations.
- 

=== Poisoned Floating Summarization

TODO


== EIGRP Route Authentication

- Supports MD5 in classic mode
- supports MD5 and SHA-256 in multi-af mode

.Task: Use MD5 password in EIGRP classic mode
----
(config-if)# ip authentication mode eigrp <asn> md5
(config-if)# ip authentication key-chain eigrp <asn> <password>
----

.Task: Use MD5 password in EIGRP named mode
----
(config-router-af-interface)# authentication mode md5
(config-router-af-interface)# authentication key-chain <sesame> 
----

.Task: Authenticate EIGRP neighbor with SHA-256 password  
----
(config-router-af-interface)# authenticate mode hmac-sha-256 <password>
----

- can be applied at the *af-interface-default* in multi-af mode

== Hello Packets and the Hold-Time Intervals
== Split Horizon

== Link Bandwidth Percentage

- by default, EIGRP packets consume  max 50% of the link bandwidth as configured by the *bandwith* command
- bandwidth configured by *bandwidth* in AS configuration and *bandwith-percent* for named configuration



== EIGRP Stub Routing
== EIGRP Stub Routing Leak Map Support



== EIGRP autonomous system configuration

.Task: Create a basic EIGRP AS system configuration 
----
(config)# router eigrp asn
(config-router)# network a.b.c.d [e.f.g.h]
----

- A maximum of 30 EIGRP can be configured
- EIGRP sends updates only interfaces in the specified networks 


== verify eigrp topology

----
show ip eigrp topology [all-links]
show ip eigrp topology [prefix/len]
----

