= Enhanced Object Tracking

- separates definition of tracked object vs action to be taken when tracked object change
- tracked object can be: interface, ip route or ip sla operation or list of objects


== Interface Tracking

- can be line protocol or ip route
- may consider the carrier delay timer
- may have a delay between the changes and the notification
- may change the polling frequency


=== Interface Line Protocol Tracking


.Task: Track the Line Protocol State Of an Interface
----
(config)# track <object-number> interface <type number> line protocol
----

=== Interface IP Routing Tracking

- The IP routing State is up if 
* ip routing is enable and active on the interface 
* known  ip address ( static, dhcp , ppp/ipcp, unnumbered ) 
* interface line protocol up 

.Task: Track the IP Routing State Of an Interface
----
(config)# track <object-number> interface <type number> ip routing
----

=== EOT Support for Carrier Delay

-  If a link fails, by default there is a two-second timer that must expire
   before an interface and the associated routes are declared as being down. If
   a link goes down and comes back up before the carrier delay timer expires,
   the down state is effectively filtered, and the rest of the software on the
   switch is not aware that a link-down event occurred. You can extend the
   timer up to 60 seconds.

- When EOT is configured on an interface, the tracking may detect the interface
  is down before a configured carrier-delay timer has expired. This is because
  EOT looks at the interface state and does not consider the carrier delay
  timer.


.Task: (Optional) Enables EOT to Consider the Carrier-Delay Timer When Tracking the Status Of an Interface. 
----
(config-track)# carrier-delay
----

.Task: (Optional) Specifies a Period Of Time (In Seconds) to Delay Communicating State Changes Of a Tracked Object. 
----
(config-track)# delay {up <seconds> [down <seconds>] | down <seconds [up <seconds>]}
----

== IP Route Tracking

- Up if the route exists in the RIB and the route is accessible
- polls the ip route state every 15 seconds


.Task: Track an Ip Route
----
(config)# track <object-number> ip route <a.b.c.d/prefix> reachability
----

.Task:(Optional) Specifies the Interval In Which the Tracking Process Polls the Tracked Object. 
----
(config)# track timer ip route { <seconds> | msec <milliseconds> } 
----

TODO: scaled metrics


== IP SLA Operation Tracking

- tracks the state or the reachability of IP SLA operations 
-

.Task: Track the Reachability Of an IP SLA Host
----
(config)# track <object-number> ip sla <operation-number> reachability
----

.Example
----
# show track 3
Device# show track 3

Track 3
   IP SLA 1 reachability
   Reachability is Up
     1 change, last change 00:00:47
   Latest operation return code: over threshold
   Latest RTT (millisecs) 4
   Tracked by:
     HSRP Ethernet0/1 3
----


== Tracked List

- can be constructed with 

* boolean expression
* treshold and weight
* treshold and percentage

.Task: Configure Tracked List Object with a Boolean Expression
----
(config)# track <list-object-number> list boolean {and | or}
(config-track)# object <object-number> [not]
----


.Task: Configure Tracked List Object with Threshold and Weight 
----
(config)# track <list-object-number> list treshold weight
(config-track)# object <object-number> [weight <number]
(config-track)# object <object-number> [weight <number]
(config-track)# treshold weight {up <number> | down <number>| up <number> down <number>  }
----



.Task: Configure Tracked List Object with Threshold and Percentage 
----
(config)# track <list-object-number> list treshold percentage
(config-track)# object <object-number> 
(config-track)# object <object-number> 
(config-track)# treshold percentage {up <number> | down <number>| up <number> down <number>  }
----

.Task: Configure Tracked List Default
----
(config-track)# default { delay | object <object-number> | treshold percentage }
----
