= GLBP

menu:Configuration Guides[First Hop Redundancy Protocols > http://www.cisco.com/c/en/us/td/docs/ios-xml/ios/ipapp_fhrp/configuration/15-mt/fhp-15-mt-book/Configuring-GLBP.html[Gateway Load Balancing Protocol] ]

- One AVG (active virtual gateway) per group
- Up to 4 primary AVFs (active virtual forwarder)
- Up to 1024 GLBP groups per physical interface

- AVG responds to all ARP requests with MAC from all participating AVF
* Not with own MAC address like HSRP
- Load-balancing
* Round-robin (default)
* Host-dependent
* Weigthed

- Multicast, 224.0.0.102, UDP port 3222
- Virtual MAC address 0007.B400._xxyy_, where xx the group and yy in (00-03)

== GLBP Packet Type

[horizontal]
Hello:: Advertise protocol info, multicast, sent by any AVG or AVF in [Speak, Standby, Active] State
Request:: Request virtual MAC, unicast sent to AVG
Reply:: Get virtual MAC, unicast sent from AVG

== Active Virtual Gateway

- Elected for each group max( priority, IP address )
- Assigns up to 4 virtual MAC address to AVFs
- Reponds to ARP request for the virtual IP address of the group
- If failed, new AVG election from AVG in listen State
- By default, no AVG preemption
- Load balancing methods
* Round-robin: by default, each AVF in turn is used for ARP
* Host-dependent: use same AVF based on the host MAC
* Weighted: use the weight value advertised by the gateway

.Task: Configure GLBP Virtual Ip Address
----
(config-if)# glbp <group:0..1023 > ip [<virtual-ip-address> [secondary]]
----

NOTE: When the glbp ip command is enabled on an interface,
the handling of proxy ARP requests is changed
(unless proxy ARP was disabled).
the AVG intercepts the ARP requests and replies to the ARP on behalf of the connected nodes.
If a forwarder in the GLBP group is active, proxy ARP requests are answered using the MAC address of the first active
forwarder in the group.
If no forwarder is active, proxy ARP responses are suppressed.

.Task: Configure GLBP Priority
----
(config-if)# glbp [<group>] priority <level=100>
----

.Task: Configure GLBP Preemption
----
(config-if)# glbp [<group>] preempt [delay minimum <seconds>]
----

.Task: Configure GLBP Load Balancing
----
(config-if)# glbp <group> load-balancing [ <host-dependent> | <round-robin> | <weighted> ]
----

.Task: Configure the Time During Which the AVG Continues to Redirect Clients to a Secondary AVF
----
(config-if)# glbp <group> timers redirect <redirect-seconds=60> <timeout-seconds=1440>
----
[NOTE]
====
- The redirect timer sets the time delay between a forwarder failing on the
  network and the AVG assuming that the forwarder will not return. The virtual
  MAC address to which the forwarder was responsible for replying is still
  given out in Address Resolution Protocol (ARP) replies, but the forwarding
  task is handled by another router in the GLBP group.

- The timeout interval is the time delay between a forwarder failing on the
   network and the MAC address for which the forwarder was responsible becoming
   inactive on all of the routers in the GLBP group. After the timeout
   interval, packets sent to this virtual MAC address will be lost. The timeout
   interval must be long enough to allow all hosts to refresh their ARP cache
   entry that contained the virtual MAC address.
====

.Task: Display Glbp Status
----
# sh glbp

FastEthernet0/0.40 - Group 1
  State is Standby
    1 state change, last state change 00:02:02
  Virtual IP address is 172.16.26.100
  Hello time 3 sec, hold time 10 sec
    Next hello sent in 2.720 secs
  Redirect time 600 sec, forwarder time-out 14400 sec
  Preemption disabled
  Active is 172.16.26.6, priority 100 (expires in 11.360 sec)
  Standby is local
  Priority 100 (default)
  Weighting 100 (default 100), thresholds: lower 1, upper 100
  Load balancing: round-robin
  Group members:
    ca02.6150.0000 (172.16.26.2) local
    ca06.618c.0000 (172.16.26.6)
  There are 2 forwarders (1 active)
  Forwarder 1
    State is Listen
    MAC address is 0007.b400.0101 (learnt)
    Owner ID is ca06.618c.0000
    Time to live: 14399.840 sec (maximum 14400 sec)
    Preemption enabled, min delay 30 sec
    Active is 172.16.26.6 (primary), weighting 100 (expires in 10.944 sec)
  Forwarder 2
    State is Active
      1 state change, last state change 00:02:08
    MAC address is 0007.b400.0102 (default)
    Owner ID is ca02.6150.0000
    Preemption enabled, min delay 30 sec
    Active is local, weighting 100
----

== Active Virtual Forwarder

- Primary AVF gets virtual MACs from AVG
- Secondary AVF learns virtual MACs from hellos
- Virtual forwarder preemptive is enabled by default with 30 seconds delay
- Uses weighting and object tracking to determine the forwarding capacity of each device in the GLBP group
* Decrement or increments the weight when the interface goes down or up
* Stops being AVF if value below lower threshold
* Resumes being AVF if value greater then upper threshold
* When multiple tracked interfaces are down, the configured weighting decrements are cumulative.


.Task: Specify GLBP Initial Weighting Value
----
(config-if)# glbp <group-number> weighting <maximum> [lower <low-value> ] [upper <up-value>]
----

.Task: Specify a Tracking Object Where GLBP Weighting Changes Based on the Availability Of the Object Being Tracked
----
(config-if)# glbp <group> weighting track <object-number> [decrement <value>]
----

.Task: Configure a Router to Take Over As (AVF) Group If the Current AVF Falls Below Its Low Weighting Threshold
----
(config-if)# glbp <group> preempt forwarder [delay minimum <seconds>]
----

== Authentication

- Supports no authentication, plain-text, or MD5 authentication

.Task: Configure Glbp Authentication
----
(config-if)# glbp authentication { text <string> | key-chain <name> }
----

