= HSRP
:icons: font

menu:Configuration Guides[First Hop Redundancy Protocols > http://www.cisco.com/c/en/us/td/docs/ios-xml/ios/ipapp_fhrp/configuration/15-mt/fhp-15-mt-book/fhp-hsrp-v2.html[HSRP Version 2] ]

== Understand

- https://www.ietf.org/rfc/rfc2281.txt[RFC 2281]
- set of routes work in concert to present the illusion of a single virtual router to the hosts on the LAN


== Protocol


=== HSRP packet

MAC header | IP header | UDP packet | HSRP Packet

.HSRP packet
["packetdiag", target="hsrp-packet"]
----
diagram {
  colwidth = 32
  node_height = 32
  default_node_color = lightyellow
  default_fontsize = 12

  * Version [len = 8]
  * Opcode [len = 8]
  * State [len = 8]
  * Hellotime [len = 8]
  * Holdtime [len = 8]
  * Priority [len = 8]
  * Group [len = 8]
  * Reserved [len = 8]
  * Authentication Data [len = 32]
  * Virtual IP Address [len = 32]
}
----


Version:: HSRP version
Opcode::
* 0: *Hello*: The router is running and is capable of becoming the active or standby router
* 1: *Coup*: The router wishes to become the active router
* 2: *Resign*: The router no longer wishes to be active router

State::

[cols="5,15,80", options="header"]
|===
| Code | State   | Description
| 0    | Initial | This is the starting state and indicates that HSRP is not running. This state is entered via a configuration change or when an interface first comes up.
| 1    | Learn   | The router has not determined the virtual IP address, and not yet seen an authenticated Hello message from the active router. In this state the router is still waiting to hear from the active router.
| 2    | Listen  | The router knows the virtual IP address, but is neither the active router nor the standby router. It listens for Hello messages from those routers.
| 4    | Speak   | The router sends periodic Hello messages and is actively participating in the election of the active and/or standby router. A router cannot enter Speak state unless it has the virtual IP address.
| 8    | Standby | The router is a candidate to become the next active router and sends periodic Hello messages. Excluding transient conditions, there MUST be at most one router in the group in Standby state.
| 16   | Active  | The router is currently forwarding packets that are sent to the group's virtual MAC address. The router sends periodic Hello messages. Excluding transient conditions, there MUST be at most one router in Active state in the group.
|===


Hellotime::
- 3 seconds by default 
- only meaningful in Hello messages 
- configured on the router or learned from authenticated Hello message from the active router

Holdtime::
- 10 seconds by default

Priority::
- default value: 100
- The higher (priority || IP address) wins 

Group::

Authentication Data::
- contains clear text password or 0x63 0x69 0x73 0x63 0x6F 0x00 0x00 0x00.
 
Virtual IP address::
- configured or learned from active router


=== Finite state machine

==== Events

[cols="5,95", options="header"]
|===
| #  | Description
| a  | HSRP is configured on an enabled interface.
| b  | HSRP is disabled on an interface or the interface is disabled.
| c  | Active timer expiry. The Active timer was set to the Holdtime when the last Hello message was seen from the active router.
| d  | Standby timer expiry. The Standby timer was set to the Holdtime when the last Hello message was seen from the standby router.
| e  | Hello timer expiry. The periodic timer for sending Hello messages has expired.
| f  | Receipt of a Hello message of higher priority from a router in Speak state.
| g  | Receipt of a Hello message of higher priority from the active router.
| h  | Receipt of a Hello message of lower priority from the active router.
| i  | Receipt of a Resign message from the active router.
| j  | Receipt of a Coup message from a higher priority router.
| k  | Receipt of a Hello message of higher priority from the standby router.
| l  | Receipt of a Hello message of lower priority from the standby router.
|===

=== Actions 

[cols="5,15,80", options="header"]
|===
| #   | Action Name                 | Actions to be taken as part of the state machine
| A   | Start Active Timer          | If this action occurred as the result of the receipt of a an authenticated Hello message from the active router, the Active timer is set to the Holdtime field in the Hello message. Otherwise the Active timer is set to the current Holdtime value in use by this router. The Active timer is then started.
| B   | Start Standby Timer         | If this action occurred as the result of the receipt of an authenticated Hello message from the standby router, the Standby timer is set to the Holdtime field in the Hello message. Otherwise the Standby timer is set to the current hold time value in use by this router. The Standby timer is then started.
| C   | Stop Active Timer           | The Active timer is stopped.
| D   | Stop Standby Timer          | The Standby timer is stopped.
| E   | Learn Parameters            | This action is taken when an authenticated message is received from the active router. If the virtual IP address for this group was not manually configured, the virtual IP address MAY be learned from the message. The router MAY learn Hellotime and Holdtime values from the message.
| F   | Send Hello Message          | The router sends a Hello message with its current State, Hellotime and Holdtime.
| G   | Send Coup Message           | The router sends a Coup message to inform the active router that there is a higher priority router available.
| H   | Send Resign Message         | The router sends a Resign message to allow another router to become the active router.
| I   | Send Gratuitous ARP Message | The router broadcasts an ARP response packet advertising the group's virtual IP address and virtual MAC address. The packet is sent using the virtual MAC address as the source MAC address in the link layer header, as well as within the ARP packet.
|===

=== Transitions

["graphviz", target="hsrp-packet"]
----
digraph finite_state_machine {
    rankdir=LR;
    node [shape = circle]

    1 [label = "1-initial"]
    2 [label = "2-learn"]
    3 [label = "3-listen"]
    4 [label = "4-speak"]
    5 [label = "5-standby"]
    6 [label = "6-active"]

    1 -> 2 [label = "a(AB)",color = orange]
    1 -> 3 [label = "a(AB)",color = orange]
    
    2 -> 1 [label = "b(CD)", color = red]
    2 -> 3 [label = "g(EAB)", color = purple]
    2 -> 3 [label = "h(EAB)", color = brown]

    3 -> 1 [label = "b(CD)", color = red]
    3 -> 4 [label = "c(AB)", color = green]
    3 -> 4 [label = "d(B)", color = blue]
    3 -> 3 [label = "g(EA)", color = purple]
    3 -> 6 [label = "h(A|BGFI)", color = brown]
    3 -> 4 [label = "i(A)", color = crimson]
    3 -> 3 [label = "k(B)", color = darksalmon]
    3 -> 4 [label = "l(D)", color = aquamarine]

    4 -> 1 [label = "b(CD)", color = red]
    4 -> 5 [label = "d(D)", color = blue]
    4 -> 4 [label = "e(F)", color = darkviolet]
    4 -> 3 [label = "f(B)"]
    4 -> 4 [label = "g(EA)", color = purple]
    4 -> 6 [label = "h(A|BGFI)", color = brown]
    4 -> 4 [label = "i(A)", color = crimson]
    4 -> 3 [label = "k(B)", color = darksalmon]
    4 -> 5 [label = "l(D)", color = aquamarine]


    5 -> 1 [label = "b(CD)", color = red]
    5 -> 6 [label = "c(CDFI)", color = green]
    5 -> 5 [label = "e(F)", color = darkviolet]
    5 -> 3 [label = "f(B)", color = deepskyblue]
    5 -> 5 [label = "g(EA)", color = purple]
    5 -> 6 [label = "h(A|BGFI)", color = brown]
    5 -> 6 [label = "i(CFI)", color = crimson]
    5 -> 3 [label = "k(B)", color = darksalmon]

    6 -> 1 [label = "b(CDH)", color = red]
    6 -> 6 [label = "e(F)", color = darkviolet]
    6 -> 4 [label = "g(AB)", color = purple]
    6 -> 6 [label = "h(G)", color = brown]
    6 -> 4 [label = "j(ABH)", color = yellow]
    6 -> 6 [label = "k(B)", color = darksalmon]
    6 -> 6 [label = "l(B)", color = aquamarine]
}
----

=== HSRP operations

- Set of routers sharing one virtual IP address and one virtual MAC address
- elect one active router with the highest (priority, IP address)
- standy router takes over if Active router fails-
- elect new standby router if standby router fails or becomes the active router.
- to minimize network traffic, only the active and standby router send periodic HSRP messages.
- a router may participate in multiple groups with seperate state and timers for each group
- unique group id per vlan
- hsrp address = 0000.0c07.ACxx (where xx is the HSRP group id)

=== HSRP features

- preemption: the router with the highest priority becomes immediately the active router by sending a *coup* message,
  The previous active router changes to the *speak* state and sends a *resign* message.

- Preempt delay: 
  * delay preemption for a configurate time period allowing the router to populate its routing table
  * delays starts when preemption starts in IOS > 12.0(9) otherwise when the router is reloaded.

- Interface tracking
  * reduce HSRP priority if the monitored interface goes down, allowing another HSRP router to become active if it has preemption enabled.
  * cumulative reduction if multiple tracked interfaces are down
  * configurable decrement value (default = 10)


- ICMP redirects supports
  * disable ICMP redirects on HSRP interfaces in IOS < 12.1(3)T
  * HSRP router redirects the endstation to the virtual IP address instead of a particular IP address


== Configure

== Verify

== Debug


== References

http://www.cisco.com/en/US/tech/tk648/tk362/technologies_tech_note09186a0080094a91.shtml#intro



