= IOS Cli


Command Line Editing Commands Command 	Meaning
Ctrl+A 	Moves cursor to beginning of the line.
Ctrl+E 	Moves cursor to end of line.
Ctrl+B 	Moves back one character.
Esc+B 	Moves back one word.
Ctrl+F 	Moves forward one character.
Esc+F 	Moves forward one word.
Ctrl+D 	Deletes a single character at the cursor.
Backspace 	Deletes a single character.
Ctrl+R 	Redisplays the command prompt and command line.
Ctrl+U 	Erases a line.
Ctrl+W 	Erases a word.
Ctrl+Z 	Ends Configuration mode and returns to EXEC.
tab 	Finishes typing a command for you.

Router Command History Command 	Meaning
Ctrl+P or Up arrow 	Shows last command entered.
Ctlr+N or Down arrow 	Shows previous commands entered.
show history 	Shows last 10 commands entered by default.
show terminal 	Shows terminal configurations and history buffer size.
terminal history size [0-256] 	Changes buffer size (max 256).


TODO How to enter a password which contains a ?

press Esc
let go
then press q
let go
then ?

TO 

.task: use conditional debug
----
# debug condition interface <intf-id>
----

=== privilege levels 

- assigned to user through *exec* authorization
- changed by user through *enable* authentication
- 0: no access
- 1: user mode access
- 15: privileged mode access 


----
sh privilege
----

=== how to decrypt username password

service password encryption

keychain 
  key
key-string 7
  
why you should use the username secret password


