= LDP

menu:Configuration Guides[MPLS > http://www.cisco.com/c/en/us/td/docs/ios-xml/ios/mp_ldp/configuration/15-mt/mp-ldp-15-mt-book.html[Label Distribution Protocol] ]

- https://tools.ietf.org/html/rfc5036[RFC 5036]
- enables peer label switch routers (LSRs) to exchange label binding information for supporting hop-by-hop forwarding in an MPLS network.
- UDP 646 (TCP 711 for TDP)
- Hellos multicast to 224.0.0.2
- Updates unicast TCP to LDP ID
- supercedes Cisco TDP


== LDP process

.Task: Enable LDP at Interface Level
----
(config-if)# mpls ip
----

.Task: Specify the label protocol
----
(config)# mpls label protocol {ldp|tdp}
----

.Task: Enable Ldp at IGP Process
----
(config-router)#mpls ldp autoconfig
----

.Task: Verify Ldp Is Enabled
----
# sh mpls interfaces
----

== Discovery Of Adjacent LDP Peers

- neigbhbor discovery UDP port 646
  * basic neighbor discovery: multicast hellos to directly connected neighbors
  * extended neighbor discovery: unicast hellos to non-directly connected neighbors

.Task: Verify that the interface is up and is sending Discovery Hello messages.
----
# sh mpls ldp discovery [all| vrf <vpn-name>] [detail]

  Local LDP Identifier:
       172.16.12.1:0
       Discovery Sources:
       Interfaces:
           Ethernet3/0 (ldp): xmit
----

- timers: hello interval (5 seconds) and holdtime (15 seconds)
----
(config)# mpls ldp discovery hello interval <sec>
(config)# mpls ldp discovery hello holdtime <sec>
----

TODO: test this command

.Task: Establish LDP session between devices that are not directed connected
----
(config)# mpls ldp neighbor targeted
----

TIP: This command can be used if you want to create LDP session that persists
even when the direct link goes down and there is alternative paths.

.Task: Respond to request for LDP targeted hellos
----
(config)# mpls ldp neighbor targeted accept
----

== LDP Sessions

in 2 steps:

- Transport connection: if the 2 peers have never established a tcp session,
create a new session
with a client (active device, highest ip address) using a random port
and the server (lowest ip addr) listening on the TCP 646 port.

----
R1#show tcp brief (state)
TCB        Local_Address   Foreign_Address
498D80D8   192.1.1.1.646   192.1.5.5.21288   ESTAB
----

- Session establishment:
 * negotiates ldp protocol version, label exchange method, timers
 * if incompatibility, sends error negotiation messages and restart the negotiation
  with initial backoff value (15 seconds) and maximum backoff value (120 seconds)

----
R1#show mpls ldp parameters

  Protocol version: 1
  Session hold time: 180 sec; keep alive interval: 60 sec
  Discovery hello: holdtime: 15 sec; interval: 5 sec
  Discovery targeted hello: holdtime: 90 sec; interval: 10 sec
  Downstream on Demand max hop count: 255
  Downstream on Demand Path Vector Limit: 255
  LDP for targeted sessions
  LDP initial/maximum backoff: 15/120 sec
  LDP loop detection: off
----

- the label exchange methods:
  * Unsolicited downstream distribution mode
  * solicited downstream distribution mode

.Task: Display the status of LDP session
----
R1#sh mpls ldp neighbor

  Peer LDP Ident: 192.1.5.5:0; Local LDP Ident 192.1.1.1:0
    TCP connection: 192.1.5.5.21288 - 192.1.1.1.646
    State: Oper; Msgs sent/rcvd: 10/11; Downstream
    Up time: 00:04:24
    LDP discovery sources:
      FastEthernet0/0, Src IP addr: 172.16.15.5
    Addresses bound to peer LDP Ident:
    172.16.15.5 192.1.5.5
----


- with keepalives (60 seconds)
----
(config)# mpls ldp holdtime <sec>
%Previously established sessions may not use the new holdtime.
----

- Keepalive timer is reset every time LDP packets or keepalives are received
- Keepalives are automatically adjusted to 1/3 of the configured holdtime
- Reset the tcp session for new timers to take effect

== LDP label binding, label spaces and identifiers

- LDP label binding: association between a destination prefix and a label

- LDP supports two types of label spaces:

* Interface-specific: An interface-specific label space uses interface resources for labels.
  ** For example, label-controlled ATM (LC-ATM) interfaces use virtual path identifiers/virtual circuit identifiers (VPIs/VCIs) for labels.
  ** Depending on its configuration, an LDP platform may support zero, one, or more interface-specific label spaces.
* Platform-wide: An LDP platform supports a single platform-wide label space for use by interfaces that can share the same labels.
  ** For Cisco platforms, all interface types, except LC-ATM, use the platform-wide label space.

LDP uses a 6-byte quantity called an LDP Identifier (or LDP ID) to name label spaces.
The LDP ID is made up of the following components:

- The first four bytes, called the LPD router ID, identify the LSR that owns the label space.
- The last two bytes, called the local label space ID, identify the label space within the LSR.
  For the platform-wide label space, the last two bytes of the LDP ID are always both 0.

The LDP ID takes the following form: <LDP router ID> : <local label space ID>
The following are examples of LPD IDs: 172.16.0.0:0 , 192.168.0.0:3

The router determines the LDP router ID as follows, if the *mpls ldp router-id* command is not executed,

1. The router examines the IP addresses of all operational interfaces.
2. If these IP addresses include loopback interface addresses, the router selects the largest loopback address as the LDP router ID.
3. Otherwise, the router selects the largest IP address pertaining to an operational interface as the LDP router ID.

The normal (default) method for determining the LDP router ID may result in a router ID that is not usable in certain situations. For example, the router might select an IP address as the LDP router ID that the routing protocol cannot advertise to a neighboring router.
The *mpls ldp router-id* command allows you to specify the IP address of an interface as the LDP router ID. Make sure the specified interface is operational so that its IP address can be used as the LDP router ID.
When you issue the mpls ldp router-id command without the force keyword, the router select selects the IP address of the specified interface (provided that the interface is operational) the next time it is necessary to select an LDP router ID, which is typically the next time the interface is shut down or the address is configured.
When you issue the mpls ldp router-id command with the force keyword, the effect of the mpls ldp router-id command depends on the current state of the specified interface:

.Task:  Define Router-Id (Recommended)
----
(config)# mpls ldp router-id <interface-type number> [force]
----
[NOTE]
====
- If the interface is up (operational) and if its IP address is not currently the LDP router ID,
  the LDP router ID changes to the IP address of the interface.
  This forced change in the LDP router ID tears down any existing LDP sessions,
  releases label bindings learned via the LDP sessions,
  and interrupts MPLS forwarding activity associated with the bindings.
- If the interface is down (not operational) when the *mpls ldp router-id* force command is issued,
  when the interface transitions to up,
  the LDP router ID changes to the IP address of the interface.
  This forced change in the LDP router ID tears down any existing LDP sessions,
  releases label bindings learned via the LDP sessions,
  and interrupts MPLS forwarding activity associated with the bindings.
====

.Task: Verify LDP Sessions
----
# sh mpls ldp neighbor
----

.Task: Troubleshoot LDP Adjacencies
----
# debug mpls ldp transport events
----

.Task: Establish a TCP connection using the physical interface IP address
----
(config-if)# mpls ldp discovery transport-address interface.
----


== LDP Session protection

- provides faster LDP convergence when a link recovers following an outage.
- protects an LDP session between directly connected neighbors or an LDP session established
  for a traffic engineering (TE) tunnel.
- uses LDP Targeted Hellos to protect LDP sessions


.Task: Enables MPLS LDP session protection
----
(config)# mpls ldp session protection [vrf <vpn-name>] [for <acl>] [duration {infinite | <seconds>}]
----

== LDP Authentication

- MD5 with same password

.Task: Specify authentication between two LDP peers
----
(config)# mpls ldp neighbor [vrf <vpn-name>] ip-address [password [0-7] <password-string> ]
----

.Task: Make the use of passwords mandatory between LDP peers
----
(config)# mpls ldp password required
----

== LDP MD5 Global Configuration

- enables LDP MD5 globally instead of on a per-peer basis.
- can set up password requirements for a set of LDP neighbors
  to prevent unauthorized peers from establishing LDP sessions and to block spoofed TCP messages.

- enhancements

* You can specify peers for which MD5 protection is required.
  This can prevent the establishment of LDP sessions with unexpected peers.

* You can configure passwords for groups of peers. This increases the scalability
of LDP password configuration management.

* The established LDP session with a peer is not automatically torn down when the
password for that peer is changed. The new password is used the next time an
LDP session is established with the peer.

* You can control when the new password is used. You can configure the new
password on the peer before forcing the use of the new password.

* If the neighboring nodes support graceful restart, then LDP sessions are
gracefully restarted. The LDP MD5 password configuration is checkpointed to the
standby Route Processors (RPs). The LDP MD5 password is used by the device when
the new active RP attempts to establish LDP sessions with neighbors after the
switchover.

TODO more


== LDP Auto-configuration

- enables you to globally enable LDP on every interface associated with an IGP instance.
- supported on OSPF and IS-IS
- provides a means to block LDP from being enabled on interfaces


.Task: Enable the MPLS LDP Autoconfiguration feature on OSPF interfaces
----
(config-router)# mpls ldp autoconfig [area <area-id>]
----
NOTE: If no area is specified, the command applies to all interfaces associated with
the OSPF process.


.Task: Enables the MPLS LDP Autoconfiguration feature on IS-IS interfaces
----
(config-router)# mpls ldp autoconfig [level 1 | level 2]
----

.Task: Disable LDP autoconfiguration on a specified interface
----
(config-if)# no mpls ldp igp  autoconfiguration
----

== LDP outbound label filtering

- By default, LDP will generate and advertise labels for every prefix found in
  the local routing table.
- Use a standard access-list to select the prefixes eligible for label generation.

.Task: Stop the generation of labels for every prefix found in the local routing table
----
(config)# no mpls ldp advertise-labels
----

.Task: Select prefixes for LDP label generation
----
(config)# mpls ldp advertise-labels for <acl>
----

== LDP Inbound Label Binding Filtering

.Task: control the label bindings a label switch router accepts from its peer LSRs.
----
(config)# mpls ldp neighbor [vrf <vpn-name>] <ip-address> labels accept <acl>
----


.Task: Verify that MPLS LDP Inbound Label Bindings are Filtered
----
# show mpls ldp neighbor [vrf <vpn-name>] [ <address> | interface] [detail]
# show ip access-list [ <acl>]
# show mpls ldp bindings
----


== LDP Graceful restart

TODO


