= MPLS

== Concepts

- mpls vpn
**   ce : no mpls-aware
**   pe : mpls and vpn aware
**   p : no vpn aware

=== MPLS label stack

.MPLS header format
["packetdiag", target= 'mpls-header-format']
----
{
  colwidth = 32
  node_height = 32
  default_node_color = lightyellow
  default_fontsize = 12

  * Label [len=20]
  * EXP [len=3]
  * S [len=1]
  * TTL [len=8]

}
----

Label:: Locally significant to the router
EXP:: Experimental, class of service
S:: Bottom-of-Stack flag 
TTL:: Time to live

=== label distribution

- protocol : ldp (default rfc 3036) or tdp (cisco)

==== dynamic discovery of adjacent ldp peers

- neigbhbor discovery UDP port 646
  * basic neighbor discovery: multicast hellos to directly connected neighbors
  * extended neighbor discovery: unicast hellos to non-directly connected neighbors

----
R1#sh mpls ldp neighbor
  Peer LDP Ident: 192.1.5.5:0; Local LDP Ident 192.1.1.1:0
    TCP connection: 192.1.5.5.21288 - 192.1.1.1.646
    State: Oper; Msgs sent/rcvd: 10/11; Downstream
    Up time: 00:04:24
    LDP discovery sources:
      FastEthernet0/0, Src IP addr: 172.16.15.5
    Addresses bound to peer LDP Ident:
    172.16.15.5 192.1.5.5
----

- timers: hello interval (5 seconds) and holdtime (15 seconds)

----
(config)# mpls ldp discovery hello interval <sec>
(config)# mpls ldp discovery hello holdtime <sec>
----
  
==== peering establishment

in 2 steps:

- transport connection: if the 2 peers have never established a tcp session, create a new session with a client (active device, highest ip address) 
using a random port and the server (lowest ip addr) listening on the TCP 646 port.

----
R1#show tcp brief (state)
TCB        Local_Address   Foreign_Address
498D80D8   192.1.1.1.646   192.1.5.5.21288   ESTAB
----

- session establishment:
 * negotiates ldp protocol version, label exchange method, timers
 * if incompatibility, sends error negotiation messages and restart the negotiation
  with initial backoff value (15 seconds) and maximum backoff value (120 seconds)

----
R1#show mpls ldp parameters
  Protocol version: 1
  Session hold time: 180 sec; keep alive interval: 60 sec
  Discovery hello: holdtime: 15 sec; interval: 5 sec
  Discovery targeted hello: holdtime: 90 sec; interval: 10 sec
  Downstream on Demand max hop count: 255
  Downstream on Demand Path Vector Limit: 255
  LDP for targeted sessions
  LDP initial/maximum backoff: 15/120 sec
  LDP loop detection: off
----

=== regulation of peer-to-peer communication and label exchange

- with keepalives (60 seconds)

----
(config)# mpls ldp holdtime <sec>
%Previously established sessions may not use the new holdtime.
----

- keepalive timer is reset every time ldp packets or keepalive are received
- keepalive are automatically adjusted to 1/3 of the configured holdtime
- you need to reset the tcp session for new timers to take effect


== label distribution and control

- methods:
  * Unsolicited downstream distribution mode
  * solicited downstream distribution mode

(to be revised )


=== Route distinguishers and route targets

http://www.cisco.com/c/en/us/td/docs/net_mgmt/ip_solution_center/3-1/mpls/user/guide/mpls/1_iscqsg.html#wp1039468[RD and RT]


RD is added to prefix when BGP vpnv4 advertised NLRI.
  - only one per NLRI
RT is Path attribute of the NLRI
  - 1 or + for each RD/prefix  
  - useful in overlapping VPNs or central service VPN offered by SP

//TODO add figure 11-17 from narbick volume 2



== Commands

----
show mpls forwarding-table
----

check http://www.cisco.com/en/US/docs/ios-xml/ios/mpls/command/mp-s2.html#wp4232274342
