= Router IP Traffic Export

== Concepts

- export IP packets received on multiple WAN or LAN interfaces 
  to a single LAN or VLAN interface
- allow IDS probe to be placed centrally and not inline with the monitored device
- allow to direct all exported traffic to a dedicated VLAM for network monitoring.

- can filter copied packets through ACL
- can sample 
- can copied incoming or outgoing traffic.

=== Restrictions

- platform: intended for software switching platforms  and not distributed platforms
- performance: delay on the outbound interface , delay increase with number of monitored interfaces and destination hosts.
- destination: the MAC address of the device that is receiving the exported traffic must be on the same VLAN or directly connected to one of the router interfaces.
- outgoing interface for exported traffic must be Ethernet (10/100/1000)


== Configuration Tasks


=== Create IP Traffic Export Profiles

----
(config)# ip traffic-export profile name
----

=== Specify the Outgoing Interface for Exported Traffic

- mandatory

----
(config-rite)# interface type number
----

=== Export Incoming and Outgoing IP Traffic on the Monitored Interface

----
(config-rite)# bidirectional
----

If this command is not enabled, only incoming traffic is exported

=== Specify the MAC Address Of the Destination Host 

- mandatory

----
(config-rite)# mac-address hhhh.hhhh.hhhh
----

=== Filter Incoming Traffic 

----
(config-rite)# incoming {access-list {standard | extended | named} | sample one-in-every integerk}
----

=== Filter Outgoing Traffic 

----
(config-rite)# outgoing {access-list {standard | extended | named} | sample one-in-every integerk}
----

- the *bidirectional* command must be enabled.
- only routed traffic is exported and not traffic originate from the device.

=== Enable IP Traffic Export on an Interface

----
(config-if)# ip traffic-export apply profile name
----


== Troubleshooting

- The *interface* and the *mac-address* are mandatory.
- otherwise, you will get errors similar to this when *show running-config* after the *ip traffic-export profile* line

-----
! no outgoing interface configured
! no destination mac-address  configured
----

- Verify IP traffic export parameters such as the monitored ingress interface, which is where the traffic is exported and outgoing and incoming IP packet.


----
debug ip traffic-export events
show ip traffic-export [interface type number | profile name]
----

== Configuration Examples

// add example from pdfs 



