= [T]FTP


- UDP 69

passive-mode vs active mode

FTP uses two TCP connections, a control connection to send commands, and a
data connection to transfer files. The control connection always uses a
destination port 21. The data connection may work in one of two modes: active
or passive.

In active mode, when a client issues a command requiring data transfer, the
server instructs the client to listen on an ephemeral port (above 1024) and
initiates a connection to the client sourced from port number 20. In this mode,
the server connects to a client on a dynamic destination port. In passive mode,
when the client needs to transfer a file, the server opens a new ephemeral port
(above 1024) and reports it to the client. The client then connects to the
ephemeral port and the data transfer begins. In this mode, the client connects
to the server on a dynamic destination port. Note that port 20 is not used in
passive mode.

== FTP Client

TODO

== FTP Server

TODO


.Task: Verify the amount of free space available on the cisco device
----
show flash
----


NOTE: If you copy a file larger than the available space,
it will be partially copied. The failure message is 'buffer overflow -xxxx/yyyy'
where xxxx bytes read from the source and yyyy bytes available on the destination.

.Task: specify the management interface used to source the TFTP traffic
----
ip tftp source-interface <interface-type interface-number>
----


