= Normal and Extended VLANs

- Administratively defined subset of switch ports that are in the same broadcast domain
- Best practice: one VLAN, one IP subnet
- Traffic inside same VLAN is layer 2 switched
- Traffic between VLANs is layer 3 routed
- Can span multiple physical switches over "trunks"

== VLAN Numbering

- VLAN ID = 12 bits

Reserved [0, 4095] ::

** Not available for use

Normal-range [1-1005]::
** Advertised and pruned by VTP v1 and v2 except vlan 1, 1002-1005
** Configured in both vlan database mode and configuration mode
** Stored in VLAN.DAT file in Flash
** Special VLANs:
*** Vlan 1 is the default Ethernet VLAN for all access ports; cannot be deleted or changed.
*** Vlan 1002-1004 : default for FDDI
*** Vlan 1002-1005 : default for Token Ring translational bridge.

Extended-range [1006-4094] ::
** Cannot be advertised or pruned by VTP v1 and v2
** Configured only in VTP transparent mode
** Stored only in the running configuration

== VLAN Trunks

- Trunk: point-to-point links for multiple VLANs between devices
- Trunking add ISL or 802.1q headers to include VLAN id.
  * ISL : Cisco proprietary, 30-bytes (26-byte header + 4-byte trailer), does not modify original frame
  * 802.1q: IEEE standard, 4-byte tag except for native VLAN, modifies original frame


== Basic Configuration

Configuring VLANs requires few steps:

. Create the VLAN Itself
. Associate the Correct Ports with VLAN


VLAN creation can be done either in VLAN database mode configuration (after *vlan database* ) or normal configuration mode

.Catalyst 3550 VLAN Database Vs Configuration Mode
[format="dsv"]
|===
VLAN Database : Configuration
vtp {domain domain-name | password password | pruning | v2-mode | {server | client | transparent}} : vtp {domain domain-name | file filename | interface name | mode {client | server | transparent} | password password | pruning | version number}
vlan vlan-id [backupcrf {enable | disable}] [mtu mtu-size] [name vlan-name] [parent parent-vlan-id] [state {suspend | active}]:  vlan vlan-id 1
show {current | proposed | difference} : No equivalent
apply | abort | reset : No equivalent
|===


== VLAN State

- Can be active or suspended

.Task: Modify the Operational State Of a VLAN
----
(config)# vlan <id>
(config-vlan)#state [active | suspend]
----





== Troubleshoot

Check "Creating ethernet VLANs on catalyst switches: troubleshoot tips"


- SVI will be in "up/down" state after being deleted
- SVI will be in "up/up" if
  * The VLAN associated with the SVI exists in the VLAN database
  * At least one trunk or access port in the "up/up" state has been assigned to the VLAN
  * Those ports in the "up/up" state are not blocked by STP


