= Normal and Extended VLANs


- administratively defined subset of switch ports that are in the same broadcast domain
- best practice: one VLAN, one IP subnet
- traffic inside same VLAN is layer 2 switched
- traffic between VLANs is layer 3 routed
- can span multiple physical switches over "trunks"


== VLAN numbering

- VLAN ID = 12 bits 

Reserved [0, 4095] ::

**  not available for use

Normal-range [1-1005]::
** advertised and pruned by VTP v1 and v2 except vlan 1, 1002-1005 
** configured in both vlan database mode and configuration mode
** stored in VLAN.DAT file in Flash 
** Special vlans:
*** Vlan 1 is the default Ethernet VLAN for all access ports; cannot be deleted or changed.
*** Vlan 1002-1004 : default for FDDI 
*** Vlan 1002-1005 : default for Token Ring translational bridge.

Extended-range [1006-4094] ::
** cannot be advertised or pruned by VTP v1 and v2
** configured only in VTP transparent mode
** stored only in the running configuration

== VLAN Trunks

- trunk: point-to-point links for multiple VLANs between devices
- trunking add ISL or 802.1q headers to include VLAN id.
  * ISL : Cisco proprietary, 30-bytes (26-byte header + 4-byte trailer), does not modify original frame
  * 802.1q: IEEE standard, 4-byte tag except for native VLAN, modifies original frame


== Basic configuration

Configuring VLANs requires few steps:

. Create the VLAN itself
. Associate the correct ports with VLAN

VLAN creation can be done either in VLAN database mode configuration (after *vlan database* ) or normal configuration mode

.Catalyst 3550 VLAN database vs configuration mode
[format="dsv"]
|===
VLAN Database : Configuration 
vtp {domain domain-name | password password | pruning | v2-mode | {server | client | transparent}} : vtp {domain domain-name | file filename | interface name | mode {client | server | transparent} | password password | pruning | version number}
vlan vlan-id [backupcrf {enable | disable}] [mtu mtu-size] [name vlan-name] [parent parent-vlan-id] [state {suspend | active}]:  vlan vlan-id 1
show {current | proposed | difference} : No equivalent
apply | abort | reset : No equivalent
|===

== Troubleshoot

Check "Creating ethernet vlans on catalyst switches: troubleshoot tips"


- SVI will be in "up/down" state after being deleted
- SVI will be in "up/up" if
  * the VLAN associated with the SVI exists in the VLAN database
  * at least one trunk or access port in the "up/up" state has been assigned to the VLAN
  * those ports in the "up/up" state are not blocked by STP


